name: Mern nginx docker

on:
  push:
    branches: ['master']
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: build test docker
        run: |
          docker build -t travis99/multi-client ./client
          docker build -t travis99/multi-backend ./backend
          docker build -t travis99/multi-nginx ./nginx
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%s')"
      - name: Generate deployment package
        run: zip -r Mern-Nginx-Docker.zip . -x '*.git*' -x '**node_modules**'
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'
      - name: deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Mern-nginx
          environment_name: Mernnginx-env
          region: ap-southeast-1
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-891869786502
          version_label: Mern-Nginx-Docker-${{ steps.format-time.outputs.replaced }}
          deployment_package: Mern-Nginx-Docker.zip
          use_existing_version_if_available: true
